# cargo-features = ["strip"]

[package]
name = "printi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# strip = "symbols"

[dependencies]
anyhow = "1.0.32"
ctrlc = "3.1.5"
libc = "0.2.73"
opencv = "0.43.1"
