# cargo-features = ["strip"]

[package]
name = "printimg"
version = "0.2.1"
authors = ["Ryota Okimatsu <oza6ut0ne@gmail.com>"]
description = "Print an imgae or a video in terminal."
license = "MIT OR Apache-2.0"
repository = "https://github.com/oza6ut0ne/printimg-rust"
categories = ["command-line-utilities", "multimedia::images", "multimedia::video"]
keywords = ["terminal", "opencv"]
readme = "README.md"
edition = "2018"

[profile.release]
# strip = "symbols"

[[bin]]
name = "printi"
path = "src/main.rs"

[features]
default = ["opencv/opencv-4", "opencv/buildtime-bindgen"]
opencv-32 = ["opencv/opencv-32", "opencv/buildtime-bindgen"]

[dependencies]
anyhow = "1.0.32"
ctrlc = "3.1.5"
libc = "0.2.73"
opencv = { version = "0.49.1", default-features = false }
