name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , use-cross: true }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , use-cross: true }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-musl     , use-cross: true }
          - { os: ubuntu-latest  , target: arm-unknown-linux-musleabi     , use-cross: true }
          - { os: macos-latest   , target: x86_64-apple-darwin            }
          - { os: windows-latest , target: x86_64-pc-windows-msvc         }
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: rustc
          args: --release --bin printi --no-default-features --features image --target ${{ matrix.job.target }} -- -C opt-level=z
      - name: Strip
        shell: bash
        run: |
          STRIP=strip
          case ${{ matrix.job.target }} in
            armv7-unknown-linux-musleabihf) sudo apt-get -y update; sudo apt-get -y install gcc-arm-linux-gnueabihf; STRIP=arm-linux-gnueabihf-strip;;
            arm-unknown-linux-musleabi) sudo apt-get -y update; sudo apt-get -y install gcc-arm-linux-gnueabi; STRIP=arm-linux-gnueabi-strip;;
            aarch64-unknown-linux-musl) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu; STRIP=aarch64-linux-gnu-strip ;;
          esac
          $STRIP target/${{ matrix.job.target }}/release/printi
        if: startsWith( matrix.job.os, 'windows') != true
      - name: Archive artifacts
        shell: bash
        run: |
          tar zcvf target/${{ matrix.job.target }}/release/printi-${{ matrix.job.target }}.tar.gz -C target/${{ matrix.job.target }}/release/ printi
        if: startsWith( matrix.job.os, 'windows') != true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.job.target }}/release/printi-*.tar.gz
            target/${{ matrix.job.target }}/release/printi.exe
